name: Continuous Integration

# This action works with pull requests and pushes
# Thanks to Crey D for his prettier CI example
on:
  pull_request:
  push:
    branches:
      - main
      
permissions:
  contents: write     # Adding this for prettier job which updates repository in unpretty cases
  
jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,md}

# This section is from Github marketplace contributor sibiraj-s:  https://github.com/sibiraj-s/action-eslint
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "<16.0.0"
      - run: npm install # or yarn install SMS: using npm install rather than npm ci  
      - uses: sibiraj-s/action-eslint@v3
        with:
          all-files: true
          token: ${{ secrets.GITHUB_TOKEN }} # optional
          eslint-args: '--ignore-path=.gitignore' # removed --quiet option for better debugging 
          extensions: 'js,jsx,ts,tsx'
          annotations: true

  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
        uses: actions/setup-node@v3
          with:
            node-version: "<16.0.0"
      - run: npm install
      - run: npm run build --if-present
      - run: CI=true npm run test
